Lecture 3 task completed
mikeivashka/phoneshop-servlet-api pull request #5
Opened 2021-02-15 19:12 UTC by mikeivashka

2021-02-16 09:37 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/model/cart/impl/CartServiceImpl.java
> +    }
Тут я не всегда делаю add, а обновляю количество товара.  С фронта приходит именно количество товара, которое должно быть в корзине, а не то, сколько нужно добавить

2021-02-16 12:45 UTC, alexandr-i requested changes

2021-02-16 12:45 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/cart/impl/CartServiceImpl.java
> +    }
Гуд

2021-02-16 12:45 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +public class Product implements Serializable {
Зашэм?

2021-02-16 12:45 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/impl/RecentProductsServiceImpl.java
> +        if (recent.size() == RECENT_PRODUCTS_SIZE + 1) {
может всё-таки dequeue чем эти мэджик намберсы?

2021-02-16 12:45 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +    public static final String NOT_A_NUMBER_MESSAGE = "Not a number";
Возможно хорошо заимеить отдельный места для разных констант.
меседжей, имён атрибутов и тд

2021-02-16 12:45 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        recentProductsService.addToRecentProducts(recentProducts, product);
Я бы тернарку перенёс уже в сервис который принимает атрибут и продукт
а то как то половина логики в сервлете половина в сервисе. там и касты все

2021-02-16 12:45 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            NumberFormat numberFormat = NumberFormat.getIntegerInstance(req.getLocale());
Вопрос чисто на подумать.
создавать NumberFormat каждый раз не очень. 1н на всех низзя т.к. не ThreadSafe
варианты?

2021-02-16 12:45 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            urlPostfix.append("?" + SUCCESS_MESSAGE_PARAMETER_NAME + "=");
Обязательную часть можно было в конструктор StringBuilder запихнуть

2021-02-16 12:45 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +                session.setAttribute(CART_ATTRIBUTE, cart);
попробуй заэкстрактить в приватный, а то и так очень большой выходит метод

2021-02-16 13:05 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +public class Product implements Serializable {
Чтобы в сессии хранить лист недавних продуктов. Они же сериализуются для хранения. По просьбе сонарлинта сделал

2021-02-16 15:34 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            NumberFormat numberFormat = NumberFormat.getIntegerInstance(req.getLocale());
Стейт намберформата может изменяться только через сеттеры, если не использовать сеттеры можно использовать один объект для всех потоков: https://stackoverflow.com/questions/1285279/java-synchronization-issue-with-numberformat
Или использовать ThreadLocal

2021-02-16 18:21 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +public class Product implements Serializable {
Сериализация конкретно нужна, чтобы если контейнер сервлет использует несколько JVM, передавать между ними сериализованные сессии

2021-02-16 19:19 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +    public static final String NOT_A_NUMBER_MESSAGE = "Not a number";
Сделано

2021-02-16 19:54 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            urlPostfix.append("?" + SUCCESS_MESSAGE_PARAMETER_NAME + "=");
Сделано

2021-02-16 21:04 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +                session.setAttribute(CART_ATTRIBUTE, cart);
Сделано

2021-02-16 21:05 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/model/product/impl/RecentProductsServiceImpl.java
> +        if (recent.size() == RECENT_PRODUCTS_SIZE + 1) {
Сделано

2021-02-16 22:08 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        recentProductsService.addToRecentProducts(recentProducts, product);
Если я все правильно понял, то сделано)

2021-02-17 12:36 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +public class Product implements Serializable {
Котовишься кластер разворачивать?

2021-02-17 12:42 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            NumberFormat numberFormat = NumberFormat.getIntegerInstance(req.getLocale());
Молодец

2021-02-17 12:43 UTC, alexandr-i approved these changes

2021-02-17 12:43 UTC, merged