Lecture-5
mikeivashka/phoneshop-servlet-api pull request #7
Opened 2021-03-01 13:51 UTC by mikeivashka

2021-03-02 15:58 UTC, alexandr-i requested changes

2021-03-02 15:58 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/order/Order.java
> +    private BigDecimal total;
total что? можно только догадываться))

2021-03-02 15:58 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/order/impl/ArrayListOrderDao.java
> +public class ArrayListOrderDao implements OrderDao {
Generic Dao будешь делать?

2021-03-02 15:58 UTC, alexandr-i commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +        <c:set var="error" value="${errors['firstName']}"/>
а что с тэгом не получилось?

2021-03-02 15:58 UTC, alexandr-i commented on src/main/webapp/WEB-INF/pages/orderOverview.jsp
> +    <label for="firstName">First name<span style="color:red">*</span></label>
и тут

2021-03-02 16:13 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/model/order/impl/ArrayListOrderDao.java
> +public class ArrayListOrderDao implements OrderDao {
В процессе

2021-03-02 16:16 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/model/order/Order.java
> +    private BigDecimal total;
упс....

2021-03-02 16:59 UTC, mikeivashka commented on src/main/java/com/es/phoneshop/model/order/impl/ArrayListOrderDao.java
> +public class ArrayListOrderDao implements OrderDao {
Кажется, что это будет лучший дженерик дао во вселенной xD

2021-03-02 17:32 UTC, mikeivashka commented on src/main/webapp/WEB-INF/pages/orderOverview.jsp
> +    <label for="firstName">First name<span style="color:red">*</span></label>
Сделано

2021-03-02 17:33 UTC, mikeivashka commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +        <c:set var="error" value="${errors['firstName']}"/>
Добавил тэг

2021-03-06 20:41 UTC, alexandr-i reviewed
Good Job

2021-03-06 20:41 UTC, alexandr-i approved these changes

2021-03-06 20:42 UTC, merged